/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2020-04-13 18:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.ORSProj3.dto.RoleDTO;
import in.co.rays.ORSProj3.controller.ORSView;
import in.co.rays.ORSProj3.dto.UserDTO;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.ORSProj3.dto.RoleDTO");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.dto.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 UserDTO userDTO=(UserDTO)session.getAttribute("user");

	boolean userLoggedIn= userDTO != null;
	
	String welcomeMsg = "Hi,";
	
	if(userLoggedIn)
	{
		String role=(String)session.getAttribute("role");
		welcomeMsg +=" "+ userDTO.getFirstName()+" (" +role+ ")";
	}
	else
	{
		welcomeMsg+="  Guest";
	}

      out.write("\r\n");
      out.write("<div class=\"navbar-wrapper\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-md bg-dark navbar-dark\">\r\n");
      out.write("  <!-- Brand/logo -->\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\">\r\n");
      out.write("    <img src=\"/ORSProj3/img/customLogo.png\" alt=\"logo\" style=\"width:150px; height:60px; margin-left: -10px; margin-bottom: -10px; margin-top: -10px\" >\r\n");
      out.write("  </a>\r\n");
      out.write("   <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("         \r\n");
      out.write("   <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("    <!-- ROLE = ADMIN -->\r\n");
      out.write("       \r\n");
      out.write("   <!-- Links -->\r\n");
      out.write("   <ul class=\"nav navbar-nav justify-content-center\">\r\n");
      out.write("    <!-- Dropdown -->\r\n");
      out.write("    <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user\"></i>&nbsp;User</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add User</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_LIST_CTL );
      out.write("\"><i class=\"fas fa-address-book\"></i>&nbsp;User List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-file-alt\"></i>&nbsp;Marksheet</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-folder-plus\"></i>&nbsp;Add Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;Marksheet List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-university\"></i>&nbsp;College</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_CTL );
      out.write("\"><i class=\"fas fa-folder-plus\"></i>&nbsp;Add College</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;College List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("     </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-tag\"></i>&nbsp;Role</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL );
      out.write("\"><i class=\"fas fa-folder-plus\"></i>&nbsp;Add Role</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;Role List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("     </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-graduate\"></i>&nbsp;Student</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add Student</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_LIST_CTL );
      out.write("\"><i class=\"fas fa-users\"></i>&nbsp;Student List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book-reader\"></i>&nbsp;Course</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL );
      out.write("\"><i class=\"fas fa-book-medical\"></i>&nbsp;Add Course</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_LIST_CTL );
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Course List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book\"></i>&nbsp;Subject</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL );
      out.write("\"><i class=\"fas fa-book-medical\"></i>&nbsp;Add Subject</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_LIST_CTL );
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Subject List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-tie\"></i>&nbsp;Faculty</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add Faculty</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_LIST_CTL );
      out.write("\"><i class=\"fas fa-address-book\"></i>&nbsp;Faculty List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"far fa-calendar-alt\"></i>&nbsp;Timetable</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL );
      out.write("\"><i class=\"far fa-calendar-plus\"></i>&nbsp;Add Timetable</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_LIST_CTL );
      out.write("\"><i class=\"far fa-calendar-check\"></i>&nbsp;Timetable List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("       </li>\r\n");
      out.write("      <a target=\"blank\" class=\"nav-link\" href=\"");
      out.print(ORSView.JAVA_DOC_VIEW );
      out.write("\" id=\"navbardrop\"><i class=\"far fa-file-alt\"></i>&nbsp;Java Doc</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <!-- Links -->\r\n");
      out.write("   <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("    <!-- Dropdown -->\r\n");
      out.write("    <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"> ");
      out.print(welcomeMsg );
      out.write(" </a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("       \r\n");
      out.write("              \r\n");
      out.write("   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\"><i class=\"fas fa-sign-out-alt\"></i>&nbsp;Logout</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MY_PROFILE_CTL );
      out.write("\"><i class=\"fas fa-user-edit\"></i>&nbsp;My Profile</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL );
      out.write("\"><i class=\"fas fa-key\"></i>&nbsp;Change Password</a>\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("           <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.LOGIN_CTL );
      out.write("\"><i class=\"fas fa-sign-in-alt\"></i>&nbsp;Login</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_REGISTRATION_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;User Registration</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FORGET_PASSWORD_CTL );
      out.write("\"><i class=\"fas fa-key\"></i>&nbsp;Forget Password</a>\r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
