/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2022-01-05 14:08:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.ORSProj3.model.SubjectModelJDBCImpl;
import in.co.rays.ORSProj3.controller.SubjectListCtl;
import in.co.rays.ORSProj3.util.HTMLUtility;
import java.util.Iterator;
import in.co.rays.ORSProj3.dto.SubjectDTO;
import in.co.rays.ORSProj3.dto.CourseDTO;
import java.util.List;
import in.co.rays.ORSProj3.util.ServletUtility;
import in.co.rays.ORSProj3.util.DataValidator;
import in.co.rays.ORSProj3.controller.LoginCtl;
import in.co.rays.ORSProj3.dto.RoleDTO;
import in.co.rays.ORSProj3.controller.ORSView;
import in.co.rays.ORSProj3.dto.UserDTO;

public final class SubjectListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1587153850194L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1587393939618L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.model.SubjectModelJDBCImpl");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.controller.SubjectListCtl");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.dto.CourseDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.dto.RoleDTO");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.controller.LoginCtl");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.util.ServletUtility");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.dto.SubjectDTO");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.util.DataValidator");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.dto.UserDTO");
    _jspx_imports_classes.add("in.co.rays.ORSProj3.util.HTMLUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16*16\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("<script src=\"");
      out.print(ORSView.APP_CONTEXT );
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(ORSView.APP_CONTEXT );
      out.write("/js/Checkbox11.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Subject List</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: url('/ORSProj3/img/455165.jpg') no-repeat center center fixed;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("input[type=text], select {\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\tpadding-left: 0px;\r\n");
      out.write("\tpadding-right: 0px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form-group i {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group i {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon {\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\tmin-width: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      in.co.rays.ORSProj3.dto.SubjectDTO dto = null;
      dto = (in.co.rays.ORSProj3.dto.SubjectDTO) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new in.co.rays.ORSProj3.dto.SubjectDTO();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 UserDTO userDTO=(UserDTO)session.getAttribute("user");

	boolean userLoggedIn= userDTO != null;
	
	String welcomeMsg = "Hi,";
	
	if(userLoggedIn)
	{
		String role=(String)session.getAttribute("role");
		welcomeMsg +=" "+ userDTO.getFirstName()+" (" +role+ ")";
	}
	else
	{
		welcomeMsg+="  Guest";
	}

      out.write("\r\n");
      out.write("<div class=\"navbar-wrapper\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-md bg-white navbar-light\">\r\n");
      out.write("  <!-- Brand/logo -->\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\">\r\n");
      out.write("    <img src=\"/ORSProj3/img/customLogo.png\" alt=\"logo\" style=\"width:150px; height:60px; margin-left: -10px; margin-bottom: -10px; margin-top: -10px\" >\r\n");
      out.write("  </a>\r\n");
      out.write("   <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("         \r\n");
      out.write("   <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("    <!-- ROLE = ADMIN -->\r\n");
      out.write("       \r\n");
      out.write("   <!-- Links -->\r\n");
      out.write("   ");
if (userLoggedIn) { 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   ");
   if(userDTO.getRoleId() == RoleDTO.ADMIN) { 
      out.write("\r\n");
      out.write("   <ul class=\"nav navbar-nav justify-content-center\">\r\n");
      out.write("    <!-- Dropdown -->\r\n");
      out.write("    <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user\"></i>&nbsp;User</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add User</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_LIST_CTL );
      out.write("\"><i class=\"fas fa-address-book\"></i>&nbsp;User List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-file-alt\"></i>&nbsp;Marksheet</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-folder-plus\"></i>&nbsp;Add Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;Marksheet List</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-graduation-cap\"></i>&nbsp;Get Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL );
      out.write("\"><i class=\"far fa-chart-bar\"></i>&nbsp;Marksheet Merit List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-university\"></i>&nbsp;College</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_CTL );
      out.write("\"><i class=\"fas fa-folder-plus\"></i>&nbsp;Add College</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;College List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("     </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-tag\"></i>&nbsp;Role</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL );
      out.write("\"><i class=\"fas fa-folder-plus\"></i>&nbsp;Add Role</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;Role List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("     </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-graduate\"></i>&nbsp;Student</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add Student</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_LIST_CTL );
      out.write("\"><i class=\"fas fa-users\"></i>&nbsp;Student List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book-reader\"></i>&nbsp;Course</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_CTL );
      out.write("\"><i class=\"fas fa-book-medical\"></i>&nbsp;Add Course</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Course List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book\"></i>&nbsp;Subject</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_CTL );
      out.write("\"><i class=\"fas fa-book-medical\"></i>&nbsp;Add Subject</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL );
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Subject List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-tie\"></i>&nbsp;Faculty</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add Faculty</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><i class=\"fas fa-address-book\"></i>&nbsp;Faculty List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"far fa-calendar-alt\"></i>&nbsp;Timetable</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_CTL );
      out.write("\"><i class=\"far fa-calendar-plus\"></i>&nbsp;Add Timetable</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\"><i class=\"far fa-calendar-check\"></i>&nbsp;Timetable List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("       </li>\r\n");
      out.write("      <a target=\"blank\" class=\"nav-link\" href=\"");
      out.print(ORSView.JAVA_DOC_VIEW );
      out.write("\" id=\"navbardrop\"><i class=\"far fa-file-alt\"></i>&nbsp;Java Doc</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write(" \r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");
 if (userDTO.getRoleId() == RoleDTO.STUDENT) { 
      out.write("\r\n");
      out.write("  \r\n");
      out.write("   <ul class=\"nav navbar-nav justify-content-center\">\r\n");
      out.write("    <!-- Dropdown -->\r\n");
      out.write(" \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-file-alt\"></i>&nbsp;Marksheet</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-graduation-cap\"></i>&nbsp;Get Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL );
      out.write("\"><i class=\"far fa-chart-bar\"></i>&nbsp;Marksheet Merit List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-university\"></i>&nbsp;College</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;College List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-graduate\"></i>&nbsp;Student</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_LIST_CTL );
      out.write("\"><i class=\"fas fa-users\"></i>&nbsp;Student List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book-reader\"></i>&nbsp;Course</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Course List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book\"></i>&nbsp;Subject</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL );
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Subject List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-tie\"></i>&nbsp;Faculty</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_LIST_CTL );
      out.write("\"><i class=\"fas fa-address-book\"></i>&nbsp;Faculty List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"far fa-calendar-alt\"></i>&nbsp;Timetable</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\"><i class=\"far fa-calendar-check\"></i>&nbsp;Timetable List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  \r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write(" \t");
  if (userDTO.getRoleId() == RoleDTO.KIOSK) { 
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write(" \t\t   <ul class=\"nav navbar-nav justify-content-center\">\r\n");
      out.write("    <!-- Dropdown -->\r\n");
      out.write("       <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-file-alt\"></i>&nbsp;Marksheet</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-graduation-cap\"></i>&nbsp;Get Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL );
      out.write("\"><i class=\"far fa-chart-bar\"></i>&nbsp;Marksheet Merit List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-university\"></i>&nbsp;College</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;College List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book-reader\"></i>&nbsp;Course</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Course List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"far fa-calendar-alt\"></i>&nbsp;Timetable</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\"><i class=\"far fa-calendar-check\"></i>&nbsp;Timetable List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write(" ");
 } 
      out.write(" \r\n");
      out.write(" ");
 if (userDTO.getRoleId() == RoleDTO.FACULTY) { 
      out.write("\r\n");
      out.write(" \t   <ul class=\"nav navbar-nav justify-content-center\">\r\n");
      out.write("    <!-- Dropdown -->\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-file-alt\"></i>&nbsp;Marksheet</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-folder-plus\"></i>&nbsp;Add Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;Marksheet List</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-graduation-cap\"></i>&nbsp;Get Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL );
      out.write("\"><i class=\"far fa-chart-bar\"></i>&nbsp;Marksheet Merit List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-university\"></i>&nbsp;College</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;College List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-graduate\"></i>&nbsp;Student</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add Student</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_LIST_CTL );
      out.write("\"><i class=\"fas fa-users\"></i>&nbsp;Student List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book-reader\"></i>&nbsp;Course</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Course List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book\"></i>&nbsp;Subject</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\"><i class=\"fas fa-book-medical\"></i>&nbsp;Add Subject</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Subject List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"far fa-calendar-alt\"></i>&nbsp;Timetable</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\"><i class=\"far fa-calendar-plus\"></i>&nbsp;Add Timetable</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\"><i class=\"far fa-calendar-check\"></i>&nbsp;Timetable List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");
 } 
      out.write('\r');
      out.write('\n');
      out.write(' ');
  if (userDTO.getRoleId() == RoleDTO.COLLEGE) { 
      out.write("\r\n");
      out.write(" \t\t  <ul class=\"nav navbar-nav justify-content-center\">\r\n");
      out.write("    <!-- Dropdown -->\r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-file-alt\"></i>&nbsp;Marksheet</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-folder-plus\"></i>&nbsp;Add Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL );
      out.write("\"><i class=\"fas fa-list\"></i>&nbsp;Marksheet List</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL );
      out.write("\"><i class=\"fas fa-graduation-cap\"></i>&nbsp;Get Marksheet</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL );
      out.write("\"><i class=\"far fa-chart-bar\"></i>&nbsp;Marksheet Merit List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-graduate\"></i>&nbsp;Student</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add Student</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_LIST_CTL );
      out.write("\"><i class=\"fas fa-users\"></i>&nbsp;Student List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book-reader\"></i>&nbsp;Course</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_CTL );
      out.write("\"><i class=\"fas fa-book-medical\"></i>&nbsp;Add Course</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Course List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-book\"></i>&nbsp;Subject</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_CTL );
      out.write("\"><i class=\"fas fa-book-medical\"></i>&nbsp;Add Subject</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL );
      out.write("\"><i class=\"fas fa-th-list\"></i>&nbsp;Subject List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"fas fa-user-tie\"></i>&nbsp;Faculty</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;Add Faculty</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><i class=\"fas fa-address-book\"></i>&nbsp;Faculty List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"><i class=\"far fa-calendar-alt\"></i>&nbsp;Timetable</a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-left\">\r\n");
      out.write("\t   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\"><i class=\"far fa-calendar-plus\"></i>&nbsp;Add Timetable</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\"><i class=\"far fa-calendar-check\"></i>&nbsp;Timetable List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");
 } 
      out.write('\r');
      out.write('\n');
      out.write(' ');
 } 
      out.write("\r\n");
      out.write("  <!-- Links -->\r\n");
      out.write("   <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("    <!-- Dropdown -->\r\n");
      out.write("    <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\"> ");
      out.print(welcomeMsg );
      out.write(" </a>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("       \r\n");
if (userLoggedIn) {
      out.write("\r\n");
      out.write("              \r\n");
      out.write("   <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\"><i class=\"fas fa-sign-out-alt\"></i>&nbsp;Logout</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MY_PROFILE_CTL );
      out.write("\"><i class=\"fas fa-user-edit\"></i>&nbsp;My Profile</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL );
      out.write("\"><i class=\"fas fa-key\"></i>&nbsp;Change Password</a>\r\n");
      out.write("        \r\n");
      out.write("       ");
 } else {
      out.write("\r\n");
      out.write("           <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.LOGIN_CTL );
      out.write("\"><i class=\"fas fa-sign-in-alt\"></i>&nbsp;Login</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_REGISTRATION_CTL );
      out.write("\"><i class=\"fas fa-user-plus\"></i>&nbsp;User Registration</a>\r\n");
      out.write("        <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FORGET_PASSWORD_CTL );
      out.write("\"><i class=\"fas fa-key\"></i>&nbsp;Forget Password</a>\r\n");
      out.write("       ");
 } 
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid bg-white border border-primary pt-2\">\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\" method=\"post\" class=\"form-inline justify-content-center py-2\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-12 pb-2\">\r\n");
      out.write("<h3 class=\"text-center\">Subject List</h3>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
if(DataValidator.isNotNull(ServletUtility.getSuccessMessage(request))) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"alert alert-success\">\r\n");
      out.write("<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
      out.write("<span><i class=\"fas fa-info-circle text-success\"></i> </span>\r\n");
      out.print(ServletUtility.getSuccessMessage(request) );
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
if(DataValidator.isNotNull(ServletUtility.getErrorMessage(request))) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"alert alert-danger alert-dismissible\">\r\n");
      out.write("<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
      out.write("<span><i class=\"fas fa-info-circle text-danger\"></i> </span>\r\n");
      out.print(ServletUtility.getErrorMessage(request) );
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<CourseDTO> clist = (List<CourseDTO>) request.getAttribute("courseList");
	List<SubjectDTO> slist = (List<SubjectDTO>) request.getAttribute("subjectList");


      out.write("\r\n");
      out.write("\r\n");

	int pageNo = ServletUtility.getPageNo(request);
	int pageSize = ServletUtility.getPageSize(request);
	int index = ((pageNo - 1)* pageSize ) + 1;
	
	List list = ServletUtility.getList(request);
	Iterator<SubjectDTO> it = list.iterator();
	
	if(list.size() != 0) {

      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("<div class=\"col-sm\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label for=\"coursename\"\t>&nbsp;Course Name :</label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<div class=\"input-group-prepend ml-1\">\r\n");
      out.write("<span class=\"input-group-text bg-white\">\r\n");
      out.write("<i class=\"fas fa-graduation-cap\"   style=\"margin-left: -4px\"></i>\r\n");
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.print(HTMLUtility.getList("coursename", String.valueOf(dto.getCourseId()), clist) );
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("&emsp;&emsp;&emsp;\r\n");
      out.write("<div class=\"col-sm\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label for=\"subjectname\"\t>&nbsp;Subject Name :</label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<div class=\"input-group-prepend ml-1\">\r\n");
      out.write("<span class=\"input-group-text bg-white\">\r\n");
      out.write("<i class=\"fas fa-book\"   style=\"margin-left: -4px\"></i>\r\n");
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.print(HTMLUtility.getList("subjectname", String.valueOf(dto.getSubjectName()), slist) );
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-sm mt-4 text-center\">\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_SEARCH );
      out.write("\" class=\"btn btn-success text-uppercase mr-3\" style=\"position:static;\">Search</button>\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_RESET );
      out.write("\" class=\"btn btn-warning text-uppercase px-3\" style=\"position: static;\">Reset</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"table-responsive my-2\">\r\n");
      out.write("<table class=\"table table-hover text-center table-light\">\r\n");
      out.write("<thead class=\"thead-light\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th><label>Select all</label><input type=\"checkbox\" id=\"select_all\" name=\"select\"></th>\r\n");
      out.write("<th>S.No.</th>\r\n");
      out.write("<th>Subject Name</th>\r\n");
      out.write("<th>Description</th>\r\n");
      out.write("<th>Course Name</th>\r\n");
      out.write("<th>Edit</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("\r\n");
  
	while (it.hasNext())
	{
		dto = it.next();
		

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><input type=\"checkbox\" class=\"checkbox\" name=\"ids\" value=\"");
      out.print(dto.getId());
      out.write("\"></td>\r\n");
      out.write("<td>");
      out.print(index++);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(dto.getSubjectName());
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(dto.getDescription());
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(dto.getCourseName());
      out.write("</td>\r\n");
      out.write("<td><a href=\"SubjectCtl?id=");
      out.print(dto.getId());
      out.write("\">Edit</a></td>\r\n");
      out.write("</tr>\r\n");

	}

      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container-fluid pt-n4 mb-4\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col\">\r\n");
if (pageNo == 1) { 
      out.write("\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_PREVIOUS );
      out.write("\" disabled class=\"btn btn-primary  btn-small ml-n3 text-uppercase\">PREVIOUS</button>\r\n");
} else { 
      out.write("\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_PREVIOUS );
      out.write("\" class=\"btn btn-primary btn-small ml-n3 text-uppercase\">PREVIOUS</button>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col text-center\">\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_DELETE );
      out.write("\"  class=\"btn btn-small btn-danger mx-n3 text-uppercase\">Delete</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col text-center\">\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_NEW );
      out.write("\"  class=\"btn btn-small btn-success mx-n3 text-uppercase\">New</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
 SubjectModelJDBCImpl model = new SubjectModelJDBCImpl(); 
      out.write("\r\n");
      out.write("<div class=\"col text-right\">\r\n");
if (list.size() < pageSize || model.nextPk() -1 == dto.getId()) {
      out.write("\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_NEXT );
      out.write("\" disabled class=\"btn btn-primary btn-small ml-n3 text-uppercase\">Next</button>\r\n");
 } else { 
      out.write("\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_NEXT );
      out.write("\" class=\"btn btn-primary btn-small ml-n3 text-uppercase\">Next</button>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo);
      out.write("\"> \r\n");
      out.write("<input type=\"hidden\" name=\"pageSize\" value=\"");
      out.print(pageSize);
      out.write("\">\r\n");
      out.write("\r\n");
 } if(list.size() == 0) { 
      out.write("\r\n");
      out.write("<div class=\"col-12 text-center\">\r\n");
      out.write("<br>\r\n");
      out.write("<button type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectListCtl.OP_BACK );
      out.write("\" class=\"btn btn-primary btn-small text-uppercase\">Back</button>\r\n");
      out.write("<br>\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<style >\r\n");
      out.write(".footer {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style > -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"page-footer fixed-bottom font-small bg-white pt-2\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("  <div class=\"footer-copyright text-center py-2\"><h5>&copy; Copyrights RAYS Technologies</h5>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
